### ISSUE TITLE
4.6 Arkitektur Artefakter (Archimate / BPMN)

### ISSUE THREAD

**Issue by majorSLATTER** [PBI22/Agil-Flask-Note-Projekt#118]
## Beskrivelse:
Enterprize arkitektur for vores system hvor der kigges på forretningslag, datalag, applikationslag og teknologi/ hardware lag. 
- Der laves lidt research først. 

## Underopgaver:
- [x] Business layer
- [x] Data layer
- [x] API/ Interface
- [x] Application layer
- [x] Technology layer

**Comment by zimula** [comment]
fixed minor issues
